export enum CreateOrderActions {
  CREATE_ORDER_FETCH_START = "CREATE_ORDER_FETCH_START",
  CREATE_ORDER_FETCH_SUCCESS = "CREATE_ORDER_FETCH_SUCCESS",
  CREATE_ORDER_FETCH_FAIL = "CREATE_ORDER_FETCH_FAIL",
  CREATE_ORDER_RESET_DATA = "CREATE_ORDER_RESET_DATA",
}
