export enum ProductListActions {
  PRODUCT_LIST_FETCH_START = "PRODUCT_LIST_FETCH_START",
  PRODUCT_LIST_FETCH_SUCCESS = "PRODUCT_LIST_FETCH_SUCCESS",
  PRODUCT_LIST_FETCH_FAIL = "PRODUCT_LIST_FETCH_FAIL",
  PRODUCT_LIST_RESET = "PRODUCT_LIST_RESET",
  PRODUCT_LIST_LOAD_MORE_START = "PRODUCT_LIST_LOAD_MORE_START",
  PRODUCT_LIST_LOAD_MORE_SUCCESS = "PRODUCT_LIST_LOAD_MORE_SUCCESS",
  PRODUCT_LIST_LOAD_MORE_FAIL = "PRODUCT_LIST_LOAD_MORE_FAIL",
}
