export enum CartActions {
  CART_FETCH_START = "CART_FETCH_START",
  CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS",
  CART_FETCH_FAIL = "CART_FETCH_FAIL",
  CART_FETCH_UPDATE_START = "CART_FETCH_UPDATE_START",
  CART_FETCH_UPDATE_SUCCESS = "CART_FETCH_UPDATE_SUCCESS",
  CART_FETCH_UPDATE_FAIL = "CART_FETCH_UPDATE_FAIL",
  CART_RESET_DATA = "CART_RESET_DATA",
  CART_CLEAR_UPDATE_ERRORS = "CART_CLEAR_UPDATE_ERRORS",
}
