export enum SingleProductActions {
  SINGLE_PRODUCT_FETCH_START = "SINGLE_PRODUCT_FETCH_START",
  SINGLE_PRODUCT_FETCH_SUCCESS = "SINGLE_PRODUCT_FETCH_SUCCESS",
  SINGLE_PRODUCT_FETCH_FAIL = "SINGLE_PRODUCT_FETCH_FAIL",
  SINGLE_PRODUCT_RESET = "SINGLE_PRODUCT_RESET",
}
