export enum UserDetailsActions {
  USER_DETAILS_FETCH_START = "USER_DETAILS_FETCH_START",
  USER_DETAILS_FETCH_SUCCESS = "USER_DETAILS_FETCH_SUCCESS",
  USER_DETAILS_FETCH_FAIL = "USER_DETAILS_FETCH_FAIL",
  USER_DETAILS_RESET_DATA = "USER_DETAILS_RESET_DATA",
}
