export enum GetOrdersActions {
  GET_ORDERS_FETCH_START = "GET_ORDERS_FETCH_START",
  GET_ORDERS_FETCH_SUCCESS = "GET_ORDERS_FETCH_SUCCESS",
  GET_ORDERS_FETCH_FAIL = "GET_ORDERS_FETCH_FAIL",
  GET_ORDERS_RESET_DATA = "GET_ORDERS_RESET_DATA",
}
